### ISSUE TITLE
Move reader mode inside new hamburger menu at top right

### ISSUE THREAD

**Issue by kaisdukes** [kaisdukes/quranic-corpus#23]

**Comment by grabani** [comment]
Need to change the Top RIGHT hand corner icon with the attached 'two line' hamburger icon:

![corpus hamburger menu icon](https://github.com/kaisdukes/wbw-prototype/assets/25469154/019a4b3e-d5fb-46d9-bcc4-1616241af11d).

The option to change to the reader mode will be an option from the menu listed presented from clicking on this icon.

**Comment by kaisdukes** [comment]
Done
