### ISSUE TITLE
CENTRE align Verse selector Column

### ISSUE THREAD

**Issue by grabani** [kaisdukes/quranic-corpus#29]
Can you please CENTER align the verse selector column.
![image](https://github.com/kaisdukes/quranic-corpus/assets/25469154/588436cd-be28-4886-9043-215b689f5392)

**Comment by kaisdukes** [comment]
Have decided not the implement this. Different browsers may decide to show the scrollbar differently. Some hide the scrollbar and some show it at different times. Now, in most browsers, if the scrollbar suddenly becomes visible, it won't change the layout. It will just overlay. So things won't always be centered. It depends if the scrollbar is visible or not. One hack is to make the verse drop down quite wide, so the scroll bar can overlay. However, this looks a bit ugly.

**Comment by kaisdukes** [comment]
Have decided not to implement this. Different browsers may decide to show the scrollbar differently. Some hide the scrollbar and some show it at different times. Now, in most browsers, if the scrollbar suddenly becomes visible, it won't change the layout. It will just overlay. So things won't always be centered. It depends if the scrollbar is visible or not. One hack is to make the verse drop down quite wide, so the scroll bar can overlay. However, this looks a bit ugly.

**Comment by kaisdukes** [comment]
Closing as not planned.

**Comment by kaisdukes** [comment]
Closing as not planned.
